services:
  # Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx-admin
    ports:
      - "7070:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - .:/var/www/html:ro
    depends_on:
      - app
    networks:
      - laravel-network

  # PHP + Laravel (PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app-admin
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: rightchoiceco_rightchoiceco
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db
    networks:
      - laravel-network

  # MySQL
  db:
    image: mysql:8.0
    container_name: mysql-db-admin
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: rightchoiceco_rightchoiceco
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel-network



networks:
  laravel-network:
    driver: bridge

volumes:
  dbdata:
